### ISSUE TITLE
li_at token expires after 15 minutes

### ISSUE THREAD

**Issue by DaanPepping** [austinoboyle/scrape-linkedin-selenium#71]
I'm trying to get the scraper to work but recently my li_at token seems to expire after 15 minutes, has linkedin updated it's authentication?

**Comment by Shivan11** [comment]
Yeah you maybe right. Although when I checked out the token, it showed that the expiry date was uptil 2021.

**Comment by austinoboyle** [comment]
In my anecdotal experience: no, LinkedIn has not set tokens to expire after 15 minutes. However, I have found that entering a password manually (eg, to change profile information) will reset authentication cookies.

Closing this issue as obsolete, since it has been dead for a while. If this is still a problem, please re-open the bug and provide more information.

**Comment by kalmanlukelin** [comment]
Hi, I also have the same issue that it would expire after 15 minutes. Although it says that it would expire in a year in the official doc. Any suggestion to extend the lifetime of the cookie?
https://www.linkedin.com/legal/l/cookie-table
